name: Build and deploy ManagementFunctionApp
on:
  push:
    branches:
    - main
env:
  AZURE_FUNCTIONAPP_NAME: JobGrabberManagementFunctionApp
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
jobs:
  build:
    runs-on: windows-latest
    strategy: 
      matrix:
        function: [WebScraperFunction]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore src/${{ matrix.function }}/${{ matrix.function }}/${{ matrix.function }}.csproj
    - name: Build
      run: dotnet build src/${{ matrix.function }}/${{ matrix.function }}/${{ matrix.function }}.csproj --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Publish
      run: | 
        dotnet publish src/${{ matrix.function }}/${{ matrix.function }}/${{ matrix.function }}.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output ./published/${{ matrix.function }}
        echo "FUNCTION_APP_PATH=./published/${{ matrix.function }}" >> $GITHUB_ENV
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.function }}
        path: ./published/${{ matrix.function }}
  deploy:
    runs-on: windows-latest
    needs: build
    strategy:
      matrix:
        function: [WebScraperFunction]
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.function }}
        path: ./published/${{ matrix.function }}
    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.JobGrabberManagementFunctionApp_EE1D }}
        package: ./published/${{ matrix.function }}
